spring.application.name=server

logging.pattern.level=%5p [%X{requestId:-}]

# Multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB

# application-secret.properties
spring.config.import=optional:application-secret.properties

# Datasource
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.access.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}

# OCR
ocr.invoke-url=${CLOVA_OCR_INVOKE_URL}
ocr.secret-key=${CLOVA_OCR_SECRET_KEY}

#  Frontend
app.oauth2.front-redirect-uri.local=http://localhost:5173/oauth/callback
app.oauth2.front-redirect-uri.deploy=https://medipass.vercel.app/oauth/callback

# KAKAO
#   Registration ??
spring.security.oauth2.client.registration.kakao.client-name=Kakao
spring.security.oauth2.client.registration.kakao.client-id=${KAKAO_CLIENT_ID}
spring.security.oauth2.client.registration.kakao.client-secret=${KAKAO_CLIENT_SECRET}
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.scope=account_email,profile_nickname,profile_image
#   Redirect URI ??
spring.security.oauth2.client.registration.kakao.redirect-uri=http://localhost:8080/login/oauth2/code/kakao
#   Provider ??
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize?prompt=login
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

# MFDS
mfds.base-url=https://apis.data.go.kr/1471000/DrugPrdtPrmsnInfoService07
mfds.service-key=${MFDS_SERVICE_KEY:}

# OpenAI
openai.base-url=https://api.openai.com/v1
openai.api-key=${OPENAI_API_KEY:}
openai.model=gpt-4o-mini
